### ISSUE TITLE
3dtiles模型旋转

### ISSUE THREAD

**Issue by engineerhe** [cesiumlab/cesium-lab-forum#8]
模型不能旋转，稍微一旋转模型就不见了fromRotationX、Y、Z都是过了，都不行
let m = tileset.modelMatrix;
let mx = Cesium.Matrix3.fromRotationY(Cesium.Math.toRadians(-1));
let rotationX = Cesium.Matrix4.fromRotationTranslation(mx);
 Cesium.Matrix4.multiply(m, rotationX, m);
 tileset._root.transform = m;

**Comment by engineerhe** [comment]
我用的是Cesium 1.59版本

**Comment by vtxf** [comment]
您旋转的方式有问题，需要用Cesium.Transforms中的方法来操作。可以在cesium文档中查看一下这个类，有多个方法。

**Comment by engineerhe** [comment]
@vtxf 谢谢，我已经解决了

**Comment by zhangwenjin** [comment]
@engineerhe 您好，请问是怎么解决的，谢谢！

**Comment by a2975569160** [comment]
sb
